# Customize the codemagic.yaml file according to your project and commit it to the root of your repository
# Check out https://docs.codemagic.io/getting-started/yaml/ for more information
# You can also download your configuration from Worklow Editor to get started

workflows:
  build-android:
    name: Build SmellSense for Android
    environment:
      vars:
        # GCLOUD_SERVICE_ACCOUNT_CREDENTIALS: Encrypted(...) # <-- Put your encrypted Google Play service account credentials here.
        FCI_KEYSTORE_PATH: /tmp/keystore.keystore
        # FCI_KEYSTORE: Encrypted(...) # <-- Put your encrypted keystore here
        # FCI_KEYSTORE_PASSWORD: Encrypted(...) # <-- Put your encrypted keystore password here
        FCI_KEY_PASSWORD: Encrypted(Z0FBQUFBQmhEbk1maUVMWjBpdWV2NzlmaTRGNjNPMHRXUHBnZ3lEY2hvR0l0VUVhclh4U09PMUFVV2F1aldwd3hnLWlTWF8yT3M1ZzBfU3Rob0hKa3U0cVMwWTFBbVg2TXBZY2RlQ2NkdkVraHFlam9zV25hd2c9) # <-- Put your encrypted key alias password here
        FCI_KEY_ALIAS: Encrypted(Z0FBQUFBQmhEbk0yZHpzSE9hSkszWGVCQlk1N09TOWpwOW80Q196Z1B0ZHRXR2FjWXFjZ0ZFMGptN2hyNEZoUDlfV1pzZFF5ZGpFWHZhOXNlckU3YkpmdEU5U20xRlIzb2c9PQ==) # <-- Put your encrypted key alias here
        # PACKAGE_NAME: "io.codemagic.flutteryaml" # <-- Put your package name here
        # GOOGLE_PLAY_TRACK: "alpha" # <-- This must be "alpha" or above.
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up key properties
        script: |
          echo $FCI_KEYSTORE | base64 --decode > /tmp/keystore.keystore
          cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
          keyPassword=$FCI_KEY_PASSWORD
          keyAlias=$FCI_KEY_ALIAS
          storeFile=/tmp/keystore.keystore
          EOF
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      # Lint
      # - name: Flutter analyze
      #  script: |
      #    cd . && flutter analyze
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build for Android
        script: flutter build appbundle
    artifacts:
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - mattyoung305@gmail.com
  build-ios:
    name: Build SmellSense for iOS
    scripts:
      - name: Build for iOS
        script: xcode-project use-profiles && flutter build ipa --debug --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/*
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - mattyoung305@gmail.com
