#
# Shared Workflow Definitions
#
definitions:
  - &check-ads-enabled
    name: Checking enabled-status of mobile ads
    script: |
      OUTPUT=$(grep -r "//String get bannerAdUnitId => BannerAd.testAdUnitId");

      if  [[ ! -z "$OUTPUT" ]]; then
        echo "Error: Test ads must be enabled in debug builds.";
        exit 1;
      fi

      exit 0;
  - &flutter-lint
    name: "Linting"
    script: flutter analyze
  - &generate-launcher-icons
    name: "Generating launcher icons"
    script: flutter pub run flutter_launcher_icons:main
  - &generate-splash-screens
    name: "Generating splash screens"
    script: flutter pub run flutter_native_splash:create
  - &cache
    cache_paths:
      - $FLUTTER_ROOT/.pub-cache # Dart cache
      - $HOME/.gradle/caches # Gradle cache
      - $HOME/Library/Caches/CocoaPods # CocoaPods cache
  - &env-android-vars
    FCI_KEYSTORE_PATH: /tmp/keystore.keystore
    FCI_KEYSTORE: Encrypted(Z0FBQUFBQmg3Q3R6TXFSN29TRTRydHRELWkyLVVDNlR2QXJyNVZPck9UcktNRWM1VnBCd01QX0w1VG1zSGRYMWl2Qnlad1dVMXpoTm04TXh3MEN6RFEyVUVpc1lXcENLejJ3X3V3N2ZSajdRRS1Xd3lVRnNUbXE0N0Q2SjFNVl9pc2ZyUF8zQjhGRjhvSkg2UGtyeVFwRFYzcmN4b3JHWllrNHVoalVaMUNOcXpoVGhfczhCU09Wcm9hM3MtTVJKTkpzZVNxQ2Q0azJVckxYSjRuSnk2aTdjZlU1RHl5M0dLS2NCVkJYNDRfSW4wOUtTdTJVbW5oaTZYcXFWTDlzUXJIM3dFdXh1bTY0ekdaV3J0NkJ6REN6SE5EQ1BFQ0FTQngzcnJsUmFLTm8zeE5qc2p1Uk5tcE5uWUVJaEJud1ppZ3cwcDc0SFVPVWJaQUwzOUNEQ1B6eHZZRi1FOTJ5d1d0UUlUR010UHBNaFkxTG5halMtM1BUbjA4azF0T3Q4OUF2cEVrcS1yWS0yWjNDZ0lWM0Jtdi1ldURfalVhRkRKU183Z3lTTFhoS0h6Qkw3cURvZGE4OTZXaERaOFVDTkx3QjFPWGVmY29ERmZDYzR4RHE3TG5qU0lIX1ZleWZiSE5IaWNwSHE3cklWRDVLM0h1cC13YUNQY2N2cTJVRTZXUWdQZEJ2aVpPY1dFUURLYy1GeTZuTU9ZTWQ2d0NFVkZ1Q3FvUVFHMW0yelpvVElodFFpSmQ4N0V2NjdNU3Z6a0ZKanV1ZV9PRFlUUldXN0pPOVNzMTBRZExiN211RHBLVW42NEkwWEt1SGtKZjZSVkRTVmg1aDVXeDFJRDZtTkJCdGJFWktmMXNhQVBjV2dDbG1KUDJVTmZvUGd1LXY5SmtrRVd5OXFUb1Y2elJiZXdjR1ROazJjcHZBVXltQjhuOXVuZnBvOGFhaG1faVdjM0pHLUJEVVFZVi1INzRFY3M4aEs4c0tjQ1M2NmFsU2NIdkZhRTBNU1ZxbzdQam56aEg4d3VOajFIeEhCUlJBMUFDSXVnSXF5MFpmS3JkekFYbUpiV280MzFDakZ3bXZ2XzNhNUVFV1R5c0dnUDl1NktoY3dGLWstc003RDlVbEU0LWxXTnluTlMyWk1wZ3p6NGtnT2QxOVZfb092YmZDa2VhLVl3NXdjbnpXSUxhcXlCWkFMVFNTQjN3LV90Yi04NmRhdW95Z1d6YXh1YUtIeFA1Q0pxOU1RSlQyb25RZUNtSnVrOVAtTnpaZ2ZrQ0k1TkFNU09qUWtWREY5VWNOS2x0WFoxc3V2dUVfQVVQQXFjUEFlNEkxYVNic2NtbHJDVVZZZk1ibzRJYk5EX2gxR3BZRUs1N3hJeWstazlwOFdMX3ZMZnBLeWZoVXc0WkZlbXREbFk1d0Zzc2gyOC1iQXRxNEpxWnAtbkdlc01NZmw2TElKYU4tUTJBVzlqLUFKM2RTOWxXRHd4NkVUQTc3cUdDWWk5X3JuazVOQ3VzMWsxNGpJaG5KTE0yeVZrcGxJZHBjY2FLeGVfbDVmMUJvaGRXUkdadWE3UkJRcUgwSkhtMjFGZDFHTlNlQk9QY1Y3RGUwa3phWDhPUUkyNjZKZ0VzMWFNaDkxOE9BZ3NzVW1YUHI4RE05cXpDUFhsRUxuMU4yRXJJMkYxYXNEbmhwbENQZUNYNlhqYlRablpSU2JtSU1DQV9nd0IyR1NwdWNMOEdOOGlKengwaG52eU40bDZDd2locWM1N1hrS2ZQSG9RYVNmRzUzVDJHLUxvUGdvZlVXWnVRbmZUVnZLNkp1WWZJc1B6U0FiM2xMQnZtMDcwLUdGTERmX24yYW50OHk1V1pyMlg4dXkydkx1eTZFc0NfV0JPQUl5dl85dnZjZHZ5a19XVlozemNKOHBLY2h5cFhka0llTHI4SWp0ZHoxcTZnNnBzUm5NcTdtWDlhaU16Y3NHNGJyZ0IwWFVhZnc2SkpKWEhHYjJFc2lYUFhlcGIza2w0UVJMa09aTk1jblJCM3dldXBuVDExSFhBT3lJRlpNeFFVeUZJUkF4anZvTHB1V1RzQ29MNnhibXMzek1rRk94SUtxTFBOc2VOMXRkck5ON3JrTEo5OExmREhRbVUteHZ2T0hsVXhTWTBJeFFfOW9FSXpkZjR6Um5hQzFUNUZkdnA5UkE3ZUpUTVM0RUFweFpVcXJNNUJtREU0OFFydl9lbXVxSUd5YWp2WnQ0N2RWSmV1VklzRnhudVAza1Z0T2YyUHNXWlBtdG53NkFhdkp2NjdyVXdKRFZ6NjV5aEx2VHdzNXY5NGF6bmZabVM3XzAwVXVUS0ZrN3Y3UktvUHlueXFHRDlDYmpnR0hWWVphQjBlN2FFeV9lTVR2R0hxeE9TZ2Ntb2JzTnN6X2xYZHJCT1dIeklEVEJqOHByMnM5NFIyNXJnaTR6UkFiekpKOEQwOWdzY3VZd3BWcnpTbEFwOTB6bVYxSWNyYjhDaTBLY01JcXJzRmJOZlItWDhJRkdNQWxsdl91UGdETWs1bEJESWRmQ2lxM1A2RHluX3B0VW90Rl9wNlBUdE9rMml0ZUJCbXdJVzZtQkk0OU85NmdhdklSU2lBY3JWMEQ0aGdDeEVUS2h6T3I0WnE4dHoyY05XdXJzeTY5bE8ycmU4RHpHdVlHOS1oNFVfMEcxSEhaeW9CNHhNY01kRzk0Y3FwR3VHNEtnWUY3RHRfWm9xYUY1RTJCSjQ3ZWtQSjlTX243aUc5WGllWmVGUTJ6RmtwZ0JCcnNzb2d4b2FzX2FJNXMyUUtiRkpaU2NiX2tOemNYMHl6d2FTejMtX1RKMDdiRnlXQ095d182UGVHaGY4MXFVbG1kWWNWaFN3SGdZd25FTV9vdFZpMEoyZHlXb3czcl9SaTVrRnJJZWxPV280Uldfa0luQUZ5MEQ2b3UwUFpFQ3liU2x3WWVGaWxObTBXZ2xnRU5ieUpkcWQ2dEFfQmRjYVFWSzhCWFB5Sm52OUtsMDdRMWxrbzBVQ1dSZzRHdUhaekhIRmJDaXZFZ0hOTUpGaDJTTU9KZjAzQVhOa191VENxdXMtcW43d3FhWEpCdkhldksxaEJIU05WcUx6WXdpdWhUQmJNdkUwb1FlLXNHaEdqQjdRMGt3T1g3YVlTM20wMHdVd0VkdnRneDE2QmdFX1NOU3BZelp0a0RxTkJmYXczV1o5OURzOWNFbDBMSWtWRDJlNE1OcHdkWjRpRl9SaVJNckNWbUdLTC1WMFRabTZkTzFyTTFrbmMzZXlGenNlNFRlSlZwNnBwakh6MkFPLWhlUDJ6NTloMDczQXdBa1NnalR5QWJoZEo5d3BHZ1pkb2ppUjVjNDRVZkhTZjg0NzFmajFOdTF3WXg2QUNIcGdBVnIyZm9WRFcySV9xQXAxcVV1a3IwY2dOQkJya2h2S1ZKTzBMdW1wN2tkOGpYcEp4YzhSTkJOOEdiU2V2eDNnV25GeVFib2dVSXhEb1Y5Yko5QUFpU3VIR2RKSHk0czl4dExvYnpFa19PTE8tTG9ldXFrUHFOOUxsS1lHeXpGRmpHMnZqX0k1OEkxaTFqQzlXMnViSXFSQ1hpMHlPUDR6RVU4MldYajhOLUF3VUo0MU91T3IwX29wc2FMTG80TFpMMWVzS180emEtdllpQ0xsMm9IMGVzXzdMX2xmTWRZMDMzRzB3aU5rQnBNeFc4QklRMlpMM3FoS0JSRmRjYlNjekMzLWZLSF9TOFB2WGdPbWRyRVVxWmxWWDVJSU9mRUtYVldaRXRWWUlKTjVBUTk4MUxpLWxVek44d2gxZTNnZS1TRFVzSHZvblREZVFfaGlYSHpqRUthTjJsMUxYMzdQUENzVE1jNENCaGZSdGdrQ0FHUFNpWXIxZzRBSmZLdVFKVTZzVGpTejlWNGhybGlrd1BYaHJzWFJ1Z2Nud1BvWEtBbVFDRklSVnBtSGpWQkM5YUt6MTJfSUtRZG1lcmptaVJwRjV6aGRnckU2aTBHdFpRVGlYZ3gyZ3ZIaktPYnA4RTNkZy1DR2Uza2R5WTNuQTNGMkpvbENsUVg5ZFhVT2hIelZveFZKQ3lqVVBnNEdMdElvOGt3LXhVeUJISms5RWVEMGZSZE5UVTZKLWpLVzU2NVBDRDRfYmZJaFNTb01kcHJ2Uk1iRnZXM3ZfRmViTTZHLWpvT3pjeVFrQzhWLWk4bDZvUkdYT2Zjemo0QmRyMW54alJQMVMxakpEeVAyVUNNeVR5VU9iamlXLWhyYlh5bU4yQ1RaUmZEZkpWQlFBRXBPNFpud3FuRzZzNGlsUzN5ejVwRHpBcm9BZVBJQkptUGpKVUZhOUVaN244cUFqMDQ2RE14bG1sS3lFVmgzSlZ1RVZ5WUZrV2hiSlpwWmFmY3YyTWUxbUJrZVlWWE9ROW12NDVkam5LemdweXdOeU5lMmx1MC1sN3VZVlhqUTVBQzY1STl5LXJPN09ub1RTSmxoREVDQjhFRnJTVnI0M01qendkWHhnRE54R3V2MGNQaXF4N21wZUpWVVRna01fcW00SjFYVUhoYmYzU1lLZjd0OElQWGprQXloeEpNeTlucDh1YUxYQ1MwUHZLV2NFVHJhajNiT0d6RjEyYkhQZ1JKczJDNnFuRWJJOVU3eTREZk10NnU3c05SNHUyTXNWVndJN3paZ3JLOHZqLUJid09XeGlQU1NLU1RWeVp0N2pFSWtXNjVDcUhQOS1xd0NzeDV2ZWx2TUE5OFoyaGN1QkV2MFc1RHF0V1cyVWhvVmtRZkIzTTFWUDJMVmhMQm9ZQlpWVUhmRlE3Z20tZXFBeXhwdzBuQmtkckpzaFhNYktlWW1zblpLSElqejVqdkJyYmpqYmVHelJvel9PY0R4SDhLT0tGYi1QTFlQcFY0eEJ5UkpHMFZJN2cxZE9mYm5LekNYaTZ2TV9kRkw0WEhjcWxPcW9jTWlpRS1OTTZfcjFXc1V6NGVhWXU4ZU1nNEJWYXhSR0pCN19uZ1dQOFp4SXJ3UFVjOW50amxlWDE2TGJNaURqR1FFRFhpRFJuLXlsS2Y0UmRQR1o5S0l0V0RqVUVUSS02d0xxd0hXLU1QQWRfaENEWEZjWldpNXdzbDZjWnRsUlNMNFZOVXhDcmxtYmUwenJqdmRVLU1wTkVpRFpBVW5TdlhURGc4VlZOQjVRbHppR214dU4xUGl2a2tkdVp6T3ZoenFpV3hnd1hKNTNHejVONVRuM3kzdVpWRlZtSVVtTGdST2dZWEU4ZUxOa3NhbEdodWVTTmZJLWgteXFSdmZtYmZTSTQ5ODVYYU5Ta1piV21rRXkxYXg0eXhuNFYwUHVSV0V3QUVHbnBvRkhDSFVGMVFUQUI1NnB3RUxtX21YclNMOUdWZ3gxU1NXNzI0bG0tUno1Wk1vTkxGU2RQUWNVaVZ6S25YVkJWcnZUdz0=)
    FCI_KEYSTORE_PASSWORD: Encrypted(Z0FBQUFBQmg3Q3R6YjljQzdoT25kLUgxZTVxejJCZzl6WkcydTc5cGpBb245OGpseEh3elc0M2s3cXo1M3h2SHRpeWFXTzQtX1dGZjRyeVVVOF8zWHdoa25GbjJ6TXk1dlE9PQ==)
    FCI_KEY_PASSWORD: Encrypted(Z0FBQUFBQmg3Q3R6Sk9sNWZRNkNSaWkxVXFTWmF3RjhRU2UwNm5jVTQ3TVFDdUFuVzhpQ3llWlBEMlhTcUlMSk1IcW5lNkdTNlpYYlpMYkEzZmpqanhndlh0a0FOX3FQSFE9PQ==)
    FCI_KEY_ALIAS: Encrypted(Z0FBQUFBQmg3Q3R6amFsQURlMml0bV9qUHltQ2t6cHdWQmNiQ1MwZUlWZ3NYZnA0ZTIza01LN0R3eW1PWEZkWlpiMWpxXzNES1JtZzFOZUFsNmRUWUkyTTFHc015c0s4OVE9PQ==)
  - &env-ios-vars
    APP_STORE_CONNECT_ISSUER_ID: 904d6bcc-e5a1-4213-90c4-7ff8cf5d303e
    APP_STORE_CONNECT_KEY_IDENTIFIER: D794H835AC
    APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmg3QmdYd1BSeG1CWHpkcjA0NFRHNDJEajJlY2pBM2pKbnROQzNweGx0SjUxZHE2Qk1jV2stWEdRSnNzTkNXSXlUMkdHOF95Yzk3eUwyZEhUMlltYzJsN1hrR0lSbXNDLUczRFRSQjA5Tk1Ua0dqTHc1ZWh6M1JucE1kMkhEcDI2YzN2VXdoZC1odE95OXNDUlFGV1ZZOG9seUdyYTJ0dk8tdlE3M2k0alJjVF95dm53UHBMdXUyQmhRUW1SakVLOFFDY2lHN2UtcjFxRzdpc0xIa2dXYWNJY0l0T1RrTWdXV2l6U1hqMGM3LWxBSWVpV2ZfTmducU5tYTZtWk1QQnNtWGFfd1ZIcUtTOUl1V3FmdzhidUZmdHNYcVRmNzBrMUttb1ZEVGRqZWZGMmpXSXhzUXo1UjFzRkNYUHVtSXQwYlhabVF2YzhGWWVFZ2g3N0Nma2ZkOUxWYUR6QUpWSTlTQ1J6RGoxZUFxOFY4NkZETkp1OFlBUXNqcW90eVlMaUJrMzctRVI5dms3bENCMHMweTZMZmZsOHhzZGtKMkFnYTIzOThzQTJaT09MTmxyTT0=)
    CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmg3QmdYQjBNaEVwNnIzdk1HNTFhbUNxMmtTZGhzcVpfVUxGMzdCeG83Wl84SXItOUJrMFlBOUlIMWNHcEJfNkdxR2c4VEVnX2lsc1VFZlRoSmdRMEpNdWpfNzZ0WU5zM0dKWmc1NFlaSlFoa1EtR25vSXNpbTJUelNvVzBtX0JOeGdTbk5pOHZzV0hQWTRSV3Z0cUJQODhSUzI4dmstUkc5VjNQZENuOGg5WlRRQk9TSzUzMG1XT1gwWVlMNUtmSTBSN0pwTnM2bFMxZm9IckVVNFV4Q0hSNkdoa3A5UEQ0UHVVYVlKSnZkam9GVlkzc3h2NkJuenYwdVZ2eW9IclR0M3BoYUJhQV9iRzhVR3hYQm9HbEZNcUM0NWdnTDRxRm5WUzZVY1hlM2lhcWlEaTRrTE4tdkhTZVh6UjRqSmRJMEdUUzVGSTlBVWxMVXpsSmoyOVp2M21rQkRtelFNbXIxQVY1S3ljUGNuWEJYYXlCQ0R0aTlERm0wT1Z6d1h4VzVINU52dmxWMEpPMk1idm9DelFGYnBtLTZDdERRMUxLNXlQY19XVVlhdlQ1d0VzaWw1S2dsNWJSeTVOblVqQUppb05YX3ZLaXNTOTkzOThKNmlicW9YUHVmN2QxcnpQQTF5T0t4SHBJNklfazBENTRjdDRrTmZzOXFOUWZFdGdURHdhelJQdV9RWWMzYnV3b2o0MlExRE4xWTNSZmx6NjY0Ykx4ajFINFRMT0R1clZheDRwbUZjSTd1djlNNlZ5TmRiTjV0Q04tdUhHdHlNVWdmTThQNlhnMGdtU3pwUVROMF9Ja1JQZ29VNm1yU0JLOENwUVJNeVNjMzFGRnhNZDJKSVJMMU5LR2s1QlIybFJkcV9SWDB6Z1llU0FqNEZQTEgxNURRdE82d0dkdXdYcC1TeXRGQ2x1UDNKRG1ZQldfdE8xSWZVc01sYmU0M28tSlFNNGNKSFV1TkdnTFZHZU5YOUF6Mm5Xa0JvTTRYVHhtd3NlSXluSHB4WnJrb2FpaXRKc05oZlNualFhUjM3NGtCWGFKaUJBek9qbExUb0VfdDRQR3JpODZkdTVQTGRMZk5jTlluLWU1NjlzZmJHSFRsN0xKOC1vSGJCTUVjVHM5ZEo1cXRTQTNXRE1hWVNUNUUzUzNoOVZPQWhPNkxfU2NpNHBNV1RLbktWNjFrZ0J1S0xnSXh6cHhreEJxSFU1czdCbkVFbVRUNW01NlJkckxZTTVTbUw1eXpwQzFvdF85RUNTSDlvQUNldjRveHptaDlRSDc2SDdoeHBQdDZwQURRZGliWnRLVXAyaWE3RnVXUmo0bVFncUphTWxzZzllNTlXd2pxaXJaQTJtR3JwUkxrcmZfNENtcVhNQzdURGhtdjBjLUx2bVV2QWowbTVtU21oSkVZOGNWMjBlQS1fTndyOXktcFl6czM3NW5TS2dhWjMyQnBlWUtzZlVCbndUVXBJaEdKd2JXV2FTTTZ3MkRpVENmbFRiWmo2elRMa0NHX2dxZmtpZTgyWTJ0OGxray1SYTQwM3VySDgzSDRTc0tWZkRqZDhEY3VEZjAyVl84MU5EcXB5UXoyNkNLZW5nTjFjeTFaZnQ0eHJKZTFnZ3RqNXh4Qno1WTdhNV90VTJLSk9sdUEtb3V3NmxpaTFvODFDV3dIX3drS2tDQXRJV2d2amVIRGFGZlBRcUJWOVhHZVlvMjZlN3k2aEhkWUJnZGI4NDl4Q0Q4Z0lOcUNvY2x4TjZmYlo5TXVVdUpONExUTUEyYkE0ZFZKRzVXN0oySGMtMUNaUy0tRkw2TnpNczBLbE9obUI1cE4yenZqZmpmRnplVTVHdm84TllZaHFhcFNUVG9adk12TlVibUdSUkMxZXFFdDJmWVBPVk9oVnp3c2FxSVlhMS1nS25yVVVxM01rQzRJLWRtczRkU2lYMnVyYUlmSV9ENmFHakxIZE4zSFZKek5zd1p1azRWSUVnM0V1d1NFU1dfNV9fMFVCWXdaX25qTk1LbDJhWFNWMVpVVzUwN1ZCZ0x3Y1dtdWFYSDFvSU5hVmlvN3JxOWZYa1IxajhUY2FWSVBNdlU5aWtGcU9tSFlNRkw0UGhqdXhsOUc5M01UTWttM0ZmOUFPZk81dHN6QVVqMEZUbldUUTFMdi14SXFNbk1VYm00NExBaExqdUpONklWWnNaTC1tbGFUYXphX0M4NkdqMS1MbE5IbVV3SDB3MjRBUi1LTkFsX3RtWVVqdERMdDNGOGVNWFFMN1VLd2xrSUlxLWh2alFaM0JTQzAwanQwV0k1cEo4VWZRNVNUNWdROFViQUF5dEtiV212WFZDemR5RW0wclJQbjBCbmxtSkRSektEZm12WWFPdTBjVVRoRy1IV1FSaFJESWRBWktFN0g1MkU1Z1FuLXljY3JZNFFlTXlSN3BoT3pzckNiZk1KTmxscS1abmFPTHBRT0RPTnlhdzdKcTV4cldicmF6MWJnVW5za2pUdEdfYzhRUkRqRmhoNjVKRXMyUDB5Wjl3RlZWVE1sZmpSSTluZUJOUkxEeHdNVTcyejl0VWw4ZUVDWFkxT3poVEFncjA5STNQVzJ1WUF6YlBwaVo2M2p4a0g2SjcxM3BrbFJuaTU3REUweFNCRUhCaFJacF9LR1l3NzBNeVBYWURta181SVFOM2J1OVg3Q296WDVSaW84T0owLU9wbW5BVkcwT3FmVUVBb2sxbEpGRGhQZS1IRDlLb2h1SXRPUEVEQmJiVFlBYUswUk1fc2NuYTdKLXM0VFZweU1fcDhSWGJzN21KNG5fSmZxX3h4MXVvTGJNV1pYRE5Hd243LWRCblltLU5TN21ESzczNkRYc2lnOFVMOFRmYnBEWGp1VUdQRTJwTmlJSE9OdDJ0YzRmUkxvMmxtRXpYVkx2Rm9yRTY3NDdFUm1ZdHBzVVNhcE1Lem9ZdERSS3hZZm1SYUVMQlZnX0JmNFhmaUdGMTNnQWdBZnl4RkIwU3FEZTdFWkYwajh1MnlCNlpPOERQcVU0QmZSQ1Uwd0VtQWRkR0d2dWJZQmRpeXpfWEV2SUtVRkV3MWU1Q3BW)
  - &env-builders
    flutter: stable
    xcode: latest
    cocoapods: default
  - &env-max-build-duration
    60
  - &artifacts-all
    - build/**/outputs/bundle/**/*.aab
    - build/ios/ipa/*.ipa
    - flutter_drive.log
  - &publishing
    email:
        recipients:
          - mattyoung305@gmail.com

# 
# Workflows
#
workflows:
  build-android:
    name: Build for Android
    max_build_duration: *env-max-build-duration
    environment:
      vars:
        *env-android-vars
      flutter: stable
      xcode: latest
      cocoapods: default
    cache: *cache
    scripts:
      - *flutter-lint
      - *check-ads-enabled
      - *generate-launcher-icons
      - *generate-splash-screens
      - name: "[Android] Setting up code signing"
        script: |
          echo $FCI_KEYSTORE | base64 --decode > $FCI_KEYSTORE_PATH
          cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$FCI_KEYSTORE_PASSWORD
          keyPassword=$FCI_KEY_PASSWORD
          keyAlias=$FCI_KEY_ALIAS
          storeFile=/tmp/keystore.keystore
          EOF
      - name: "[Flutter] Setting up SDK paths"
        script: echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - name: "[Flutter] Building app bundle"
        script: flutter build appbundle --debug
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/bundle/**/*.aab
      - build/**/outputs/**/mapping.txt
      - "*.snap"
      - build/windows/**/*.msix
      - flutter_drive.log
    
  build-ios:
    name: Build for iOS
    max_build_duration: 60
    environment:
      vars:
        *env-ios-vars
      flutter: stable
      xcode: latest
      cocoapods: default
    cache: *cache
    scripts:
      - *flutter-lint
      - *check-ads-enabled
      - *generate-launcher-icons
      - *generate-splash-screens
      - name: "[iOS] Installing Pod dependencies"
        script: find . -name "Podfile" -execdir pod install \;
      - name: "[iOS] Set up code signing"
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "za.co.smellsense" --type IOS_APP_DEVELOPMENT --create
          keychain add-certificates
      - name: "[iOS] Configure xcode profile"
        script: xcode-project use-profiles
      - name: "[Flutter] Build IPA"
        script: flutter build ipa --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - "*.snap"
      - build/windows/**/*.msix
      - flutter_drive.log
